// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: collector/colelctor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectKnobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectKnobsRequest) Reset() {
	*x = CollectKnobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectKnobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectKnobsRequest) ProtoMessage() {}

func (x *CollectKnobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectKnobsRequest.ProtoReflect.Descriptor instead.
func (*CollectKnobsRequest) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{0}
}

type CollectKnobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Knobs []*CollectKnobsResponse_Knob `protobuf:"bytes,1,rep,name=knobs,proto3" json:"knobs,omitempty"`
}

func (x *CollectKnobsResponse) Reset() {
	*x = CollectKnobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectKnobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectKnobsResponse) ProtoMessage() {}

func (x *CollectKnobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectKnobsResponse.ProtoReflect.Descriptor instead.
func (*CollectKnobsResponse) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{1}
}

func (x *CollectKnobsResponse) GetKnobs() []*CollectKnobsResponse_Knob {
	if x != nil {
		return x.Knobs
	}
	return nil
}

type CollectInternalMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectInternalMetricsRequest) Reset() {
	*x = CollectInternalMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectInternalMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectInternalMetricsRequest) ProtoMessage() {}

func (x *CollectInternalMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectInternalMetricsRequest.ProtoReflect.Descriptor instead.
func (*CollectInternalMetricsRequest) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{2}
}

type CollectInternalMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*CollectInternalMetricsResponse_Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *CollectInternalMetricsResponse) Reset() {
	*x = CollectInternalMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectInternalMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectInternalMetricsResponse) ProtoMessage() {}

func (x *CollectInternalMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectInternalMetricsResponse.ProtoReflect.Descriptor instead.
func (*CollectInternalMetricsResponse) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{3}
}

func (x *CollectInternalMetricsResponse) GetMetrics() []*CollectInternalMetricsResponse_Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type CollectExternalMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectExternalMetricsRequest) Reset() {
	*x = CollectExternalMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectExternalMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectExternalMetricsRequest) ProtoMessage() {}

func (x *CollectExternalMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectExternalMetricsRequest.ProtoReflect.Descriptor instead.
func (*CollectExternalMetricsRequest) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{4}
}

type CollectExternalMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tps     float32 `protobuf:"fixed32,1,opt,name=tps,proto3" json:"tps,omitempty"`
	Latency float32 `protobuf:"fixed32,2,opt,name=latency,proto3" json:"latency,omitempty"`
}

func (x *CollectExternalMetricsResponse) Reset() {
	*x = CollectExternalMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectExternalMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectExternalMetricsResponse) ProtoMessage() {}

func (x *CollectExternalMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectExternalMetricsResponse.ProtoReflect.Descriptor instead.
func (*CollectExternalMetricsResponse) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{5}
}

func (x *CollectExternalMetricsResponse) GetTps() float32 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *CollectExternalMetricsResponse) GetLatency() float32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

type InitLoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitLoadRequest) Reset() {
	*x = InitLoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLoadRequest) ProtoMessage() {}

func (x *InitLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLoadRequest.ProtoReflect.Descriptor instead.
func (*InitLoadRequest) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{6}
}

type InitLoadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitLoadResponse) Reset() {
	*x = InitLoadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLoadResponse) ProtoMessage() {}

func (x *InitLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLoadResponse.ProtoReflect.Descriptor instead.
func (*InitLoadResponse) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{7}
}

type SetKnobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Knobs []*SetKnobsRequest_Knob `protobuf:"bytes,1,rep,name=knobs,proto3" json:"knobs,omitempty"`
}

func (x *SetKnobsRequest) Reset() {
	*x = SetKnobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetKnobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKnobsRequest) ProtoMessage() {}

func (x *SetKnobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKnobsRequest.ProtoReflect.Descriptor instead.
func (*SetKnobsRequest) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{8}
}

func (x *SetKnobsRequest) GetKnobs() []*SetKnobsRequest_Knob {
	if x != nil {
		return x.Knobs
	}
	return nil
}

type SetKnobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetKnobsResponse) Reset() {
	*x = SetKnobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetKnobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKnobsResponse) ProtoMessage() {}

func (x *SetKnobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKnobsResponse.ProtoReflect.Descriptor instead.
func (*SetKnobsResponse) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{9}
}

type CollectKnobsResponse_Knob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinValue float32 `protobuf:"fixed32,2,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue float32 `protobuf:"fixed32,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	// Types that are assignable to Value:
	//
	//	*CollectKnobsResponse_Knob_StrValue
	//	*CollectKnobsResponse_Knob_FloatValue
	//	*CollectKnobsResponse_Knob_BoolValue
	Value isCollectKnobsResponse_Knob_Value `protobuf_oneof:"value"`
}

func (x *CollectKnobsResponse_Knob) Reset() {
	*x = CollectKnobsResponse_Knob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectKnobsResponse_Knob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectKnobsResponse_Knob) ProtoMessage() {}

func (x *CollectKnobsResponse_Knob) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectKnobsResponse_Knob.ProtoReflect.Descriptor instead.
func (*CollectKnobsResponse_Knob) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CollectKnobsResponse_Knob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectKnobsResponse_Knob) GetMinValue() float32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *CollectKnobsResponse_Knob) GetMaxValue() float32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (m *CollectKnobsResponse_Knob) GetValue() isCollectKnobsResponse_Knob_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *CollectKnobsResponse_Knob) GetStrValue() string {
	if x, ok := x.GetValue().(*CollectKnobsResponse_Knob_StrValue); ok {
		return x.StrValue
	}
	return ""
}

func (x *CollectKnobsResponse_Knob) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*CollectKnobsResponse_Knob_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *CollectKnobsResponse_Knob) GetBoolValue() bool {
	if x, ok := x.GetValue().(*CollectKnobsResponse_Knob_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

type isCollectKnobsResponse_Knob_Value interface {
	isCollectKnobsResponse_Knob_Value()
}

type CollectKnobsResponse_Knob_StrValue struct {
	StrValue string `protobuf:"bytes,4,opt,name=str_value,json=strValue,proto3,oneof"`
}

type CollectKnobsResponse_Knob_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type CollectKnobsResponse_Knob_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*CollectKnobsResponse_Knob_StrValue) isCollectKnobsResponse_Knob_Value() {}

func (*CollectKnobsResponse_Knob_FloatValue) isCollectKnobsResponse_Knob_Value() {}

func (*CollectKnobsResponse_Knob_BoolValue) isCollectKnobsResponse_Knob_Value() {}

type CollectInternalMetricsResponse_Metric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//
	//	*CollectInternalMetricsResponse_Metric_StrValue
	//	*CollectInternalMetricsResponse_Metric_FloatValue
	//	*CollectInternalMetricsResponse_Metric_BoolValue
	Value isCollectInternalMetricsResponse_Metric_Value `protobuf_oneof:"value"`
	Scope string                                        `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
}

func (x *CollectInternalMetricsResponse_Metric) Reset() {
	*x = CollectInternalMetricsResponse_Metric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectInternalMetricsResponse_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectInternalMetricsResponse_Metric) ProtoMessage() {}

func (x *CollectInternalMetricsResponse_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectInternalMetricsResponse_Metric.ProtoReflect.Descriptor instead.
func (*CollectInternalMetricsResponse_Metric) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CollectInternalMetricsResponse_Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *CollectInternalMetricsResponse_Metric) GetValue() isCollectInternalMetricsResponse_Metric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *CollectInternalMetricsResponse_Metric) GetStrValue() string {
	if x, ok := x.GetValue().(*CollectInternalMetricsResponse_Metric_StrValue); ok {
		return x.StrValue
	}
	return ""
}

func (x *CollectInternalMetricsResponse_Metric) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*CollectInternalMetricsResponse_Metric_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *CollectInternalMetricsResponse_Metric) GetBoolValue() bool {
	if x, ok := x.GetValue().(*CollectInternalMetricsResponse_Metric_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *CollectInternalMetricsResponse_Metric) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type isCollectInternalMetricsResponse_Metric_Value interface {
	isCollectInternalMetricsResponse_Metric_Value()
}

type CollectInternalMetricsResponse_Metric_StrValue struct {
	StrValue string `protobuf:"bytes,2,opt,name=str_value,json=strValue,proto3,oneof"`
}

type CollectInternalMetricsResponse_Metric_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type CollectInternalMetricsResponse_Metric_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*CollectInternalMetricsResponse_Metric_StrValue) isCollectInternalMetricsResponse_Metric_Value() {
}

func (*CollectInternalMetricsResponse_Metric_FloatValue) isCollectInternalMetricsResponse_Metric_Value() {
}

func (*CollectInternalMetricsResponse_Metric_BoolValue) isCollectInternalMetricsResponse_Metric_Value() {
}

type SetKnobsRequest_Knob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetKnobsRequest_Knob) Reset() {
	*x = SetKnobsRequest_Knob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_colelctor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetKnobsRequest_Knob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKnobsRequest_Knob) ProtoMessage() {}

func (x *SetKnobsRequest_Knob) ProtoReflect() protoreflect.Message {
	mi := &file_collector_colelctor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKnobsRequest_Knob.ProtoReflect.Descriptor instead.
func (*SetKnobsRequest_Knob) Descriptor() ([]byte, []int) {
	return file_collector_colelctor_proto_rawDescGZIP(), []int{8, 0}
}

func (x *SetKnobsRequest_Knob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetKnobsRequest_Knob) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_collector_colelctor_proto protoreflect.FileDescriptor

var file_collector_colelctor_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x6f, 0x6c, 0x65,
	0x6c, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x95, 0x02,
	0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x6b, 0x6e, 0x6f, 0x62, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4b, 0x6e, 0x6f, 0x62, 0x52, 0x05, 0x6b, 0x6e, 0x6f,
	0x62, 0x73, 0x1a, 0xc0, 0x01, 0x0a, 0x04, 0x4b, 0x6e, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x61, 0x78, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x73, 0x74, 0x72,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08,
	0x73, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52,
	0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62,
	0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x02, 0x0a, 0x1e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x07, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x07, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x9e, 0x01, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x42, 0x07, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x1e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x70, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x74, 0x70, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6c, 0x61,
	0x74, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x49, 0x6e, 0x69, 0x74, 0x4c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x49, 0x6e, 0x69, 0x74,
	0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7a, 0x0a, 0x0f,
	0x53, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x35, 0x0a, 0x05, 0x6b, 0x6e, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x4b, 0x6e,
	0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4b, 0x6e, 0x6f, 0x62, 0x52,
	0x05, 0x6b, 0x6e, 0x6f, 0x62, 0x73, 0x1a, 0x30, 0x0a, 0x04, 0x4b, 0x6e, 0x6f, 0x62, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x4b,
	0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc4, 0x03, 0x0a,
	0x09, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x4f, 0x0a, 0x0c, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e,
	0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e,
	0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x16, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x28, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x16, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x12, 0x28, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x49, 0x6e, 0x69,
	0x74, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e,
	0x69, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x08, 0x53, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collector_colelctor_proto_rawDescOnce sync.Once
	file_collector_colelctor_proto_rawDescData = file_collector_colelctor_proto_rawDesc
)

func file_collector_colelctor_proto_rawDescGZIP() []byte {
	file_collector_colelctor_proto_rawDescOnce.Do(func() {
		file_collector_colelctor_proto_rawDescData = protoimpl.X.CompressGZIP(file_collector_colelctor_proto_rawDescData)
	})
	return file_collector_colelctor_proto_rawDescData
}

var file_collector_colelctor_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_collector_colelctor_proto_goTypes = []interface{}{
	(*CollectKnobsRequest)(nil),                   // 0: collector.CollectKnobsRequest
	(*CollectKnobsResponse)(nil),                  // 1: collector.CollectKnobsResponse
	(*CollectInternalMetricsRequest)(nil),         // 2: collector.CollectInternalMetricsRequest
	(*CollectInternalMetricsResponse)(nil),        // 3: collector.CollectInternalMetricsResponse
	(*CollectExternalMetricsRequest)(nil),         // 4: collector.CollectExternalMetricsRequest
	(*CollectExternalMetricsResponse)(nil),        // 5: collector.CollectExternalMetricsResponse
	(*InitLoadRequest)(nil),                       // 6: collector.InitLoadRequest
	(*InitLoadResponse)(nil),                      // 7: collector.InitLoadResponse
	(*SetKnobsRequest)(nil),                       // 8: collector.SetKnobsRequest
	(*SetKnobsResponse)(nil),                      // 9: collector.SetKnobsResponse
	(*CollectKnobsResponse_Knob)(nil),             // 10: collector.CollectKnobsResponse.Knob
	(*CollectInternalMetricsResponse_Metric)(nil), // 11: collector.CollectInternalMetricsResponse.Metric
	(*SetKnobsRequest_Knob)(nil),                  // 12: collector.SetKnobsRequest.Knob
}
var file_collector_colelctor_proto_depIdxs = []int32{
	10, // 0: collector.CollectKnobsResponse.knobs:type_name -> collector.CollectKnobsResponse.Knob
	11, // 1: collector.CollectInternalMetricsResponse.metrics:type_name -> collector.CollectInternalMetricsResponse.Metric
	12, // 2: collector.SetKnobsRequest.knobs:type_name -> collector.SetKnobsRequest.Knob
	0,  // 3: collector.Collector.CollectKnobs:input_type -> collector.CollectKnobsRequest
	2,  // 4: collector.Collector.CollectInternalMetrics:input_type -> collector.CollectInternalMetricsRequest
	4,  // 5: collector.Collector.CollectExternalMetrics:input_type -> collector.CollectExternalMetricsRequest
	6,  // 6: collector.Collector.InitLoad:input_type -> collector.InitLoadRequest
	8,  // 7: collector.Collector.SetKnobs:input_type -> collector.SetKnobsRequest
	1,  // 8: collector.Collector.CollectKnobs:output_type -> collector.CollectKnobsResponse
	3,  // 9: collector.Collector.CollectInternalMetrics:output_type -> collector.CollectInternalMetricsResponse
	5,  // 10: collector.Collector.CollectExternalMetrics:output_type -> collector.CollectExternalMetricsResponse
	7,  // 11: collector.Collector.InitLoad:output_type -> collector.InitLoadResponse
	9,  // 12: collector.Collector.SetKnobs:output_type -> collector.SetKnobsResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_collector_colelctor_proto_init() }
func file_collector_colelctor_proto_init() {
	if File_collector_colelctor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collector_colelctor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectKnobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectKnobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectInternalMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectInternalMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectExternalMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectExternalMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitLoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitLoadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetKnobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetKnobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectKnobsResponse_Knob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectInternalMetricsResponse_Metric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_colelctor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetKnobsRequest_Knob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_collector_colelctor_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*CollectKnobsResponse_Knob_StrValue)(nil),
		(*CollectKnobsResponse_Knob_FloatValue)(nil),
		(*CollectKnobsResponse_Knob_BoolValue)(nil),
	}
	file_collector_colelctor_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*CollectInternalMetricsResponse_Metric_StrValue)(nil),
		(*CollectInternalMetricsResponse_Metric_FloatValue)(nil),
		(*CollectInternalMetricsResponse_Metric_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collector_colelctor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_colelctor_proto_goTypes,
		DependencyIndexes: file_collector_colelctor_proto_depIdxs,
		MessageInfos:      file_collector_colelctor_proto_msgTypes,
	}.Build()
	File_collector_colelctor_proto = out.File
	file_collector_colelctor_proto_rawDesc = nil
	file_collector_colelctor_proto_goTypes = nil
	file_collector_colelctor_proto_depIdxs = nil
}
