version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shared_network

  db:
    networks:
      - shared_network
    image: postgres:latest
    container_name: "postgresdb"
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all &&
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: pg_stat_statements
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: "envapp"
    networks:
      - shared_network
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    ports:
      - "7002:7002"
    depends_on:
      db:
        condition: service_healthy

networks:
  shared_network:
    external: true