grpc:
  host: "localhost"
  port: 7003
collector:
  host: "localhost"

postgres:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  database: "postgres"
  container_name: "postgresdb"