// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: recommendations_api/recommendations_api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
}

func (x *GetStatesRequest) Reset() {
	*x = GetStatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatesRequest) ProtoMessage() {}

func (x *GetStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatesRequest.ProtoReflect.Descriptor instead.
func (*GetStatesRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatesRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type GetStatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*GetStatesResponse_Metric `protobuf:"bytes,1,rep,name=Metrics,proto3" json:"Metrics,omitempty"`
}

func (x *GetStatesResponse) Reset() {
	*x = GetStatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatesResponse) ProtoMessage() {}

func (x *GetStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatesResponse.ProtoReflect.Descriptor instead.
func (*GetStatesResponse) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatesResponse) GetMetrics() []*GetStatesResponse_Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ApplyActionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string                    `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Knobs        *ApplyActionsRequest_Knob `protobuf:"bytes,2,opt,name=knobs,proto3" json:"knobs,omitempty"`
}

func (x *ApplyActionsRequest) Reset() {
	*x = ApplyActionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyActionsRequest) ProtoMessage() {}

func (x *ApplyActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyActionsRequest.ProtoReflect.Descriptor instead.
func (*ApplyActionsRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyActionsRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *ApplyActionsRequest) GetKnobs() *ApplyActionsRequest_Knob {
	if x != nil {
		return x.Knobs
	}
	return nil
}

type ApplyActionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyActionsResponse) Reset() {
	*x = ApplyActionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyActionsResponse) ProtoMessage() {}

func (x *ApplyActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyActionsResponse.ProtoReflect.Descriptor instead.
func (*ApplyActionsResponse) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{3}
}

type GetRewardMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
}

func (x *GetRewardMetricsRequest) Reset() {
	*x = GetRewardMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRewardMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRewardMetricsRequest) ProtoMessage() {}

func (x *GetRewardMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRewardMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetRewardMetricsRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetRewardMetricsRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type GetRewardMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latency float32 `protobuf:"fixed32,1,opt,name=latency,proto3" json:"latency,omitempty"`
	Tps     float32 `protobuf:"fixed32,2,opt,name=tps,proto3" json:"tps,omitempty"`
}

func (x *GetRewardMetricsResponse) Reset() {
	*x = GetRewardMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRewardMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRewardMetricsResponse) ProtoMessage() {}

func (x *GetRewardMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRewardMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetRewardMetricsResponse) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetRewardMetricsResponse) GetLatency() float32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *GetRewardMetricsResponse) GetTps() float32 {
	if x != nil {
		return x.Tps
	}
	return 0
}

type InitEnvironmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
}

func (x *InitEnvironmentRequest) Reset() {
	*x = InitEnvironmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEnvironmentRequest) ProtoMessage() {}

func (x *InitEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*InitEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{6}
}

func (x *InitEnvironmentRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type InitEnvironmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitEnvironmentResponse) Reset() {
	*x = InitEnvironmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEnvironmentResponse) ProtoMessage() {}

func (x *InitEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*InitEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{7}
}

type GetStatesResponse_Metric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetStatesResponse_Metric) Reset() {
	*x = GetStatesResponse_Metric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatesResponse_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatesResponse_Metric) ProtoMessage() {}

func (x *GetStatesResponse_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatesResponse_Metric.ProtoReflect.Descriptor instead.
func (*GetStatesResponse_Metric) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetStatesResponse_Metric) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ApplyActionsRequest_Knob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ApplyActionsRequest_Knob) Reset() {
	*x = ApplyActionsRequest_Knob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_api_recommendations_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyActionsRequest_Knob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyActionsRequest_Knob) ProtoMessage() {}

func (x *ApplyActionsRequest_Knob) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_api_recommendations_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyActionsRequest_Knob.ProtoReflect.Descriptor instead.
func (*ApplyActionsRequest_Knob) Descriptor() ([]byte, []int) {
	return file_recommendations_api_recommendations_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ApplyActionsRequest_Knob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyActionsRequest_Knob) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_recommendations_api_recommendations_api_proto protoreflect.FileDescriptor

var file_recommendations_api_recommendations_api_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x37, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x72, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x07,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x1e, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x6b, 0x6e, 0x6f, 0x62, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x4b, 0x6e, 0x6f, 0x62, 0x52, 0x05, 0x6b, 0x6e, 0x6f, 0x62, 0x73, 0x1a,
	0x30, 0x0a, 0x04, 0x4b, 0x6e, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x74, 0x70,
	0x73, 0x22, 0x3d, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe4, 0x02, 0x0a, 0x12,
	0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x41,
	0x50, 0x49, 0x12, 0x46, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12,
	0x1b, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12,
	0x22, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x49, 0x6e, 0x69, 0x74,
	0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recommendations_api_recommendations_api_proto_rawDescOnce sync.Once
	file_recommendations_api_recommendations_api_proto_rawDescData = file_recommendations_api_recommendations_api_proto_rawDesc
)

func file_recommendations_api_recommendations_api_proto_rawDescGZIP() []byte {
	file_recommendations_api_recommendations_api_proto_rawDescOnce.Do(func() {
		file_recommendations_api_recommendations_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_recommendations_api_recommendations_api_proto_rawDescData)
	})
	return file_recommendations_api_recommendations_api_proto_rawDescData
}

var file_recommendations_api_recommendations_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_recommendations_api_recommendations_api_proto_goTypes = []interface{}{
	(*GetStatesRequest)(nil),         // 0: collector.GetStatesRequest
	(*GetStatesResponse)(nil),        // 1: collector.GetStatesResponse
	(*ApplyActionsRequest)(nil),      // 2: collector.ApplyActionsRequest
	(*ApplyActionsResponse)(nil),     // 3: collector.ApplyActionsResponse
	(*GetRewardMetricsRequest)(nil),  // 4: collector.GetRewardMetricsRequest
	(*GetRewardMetricsResponse)(nil), // 5: collector.GetRewardMetricsResponse
	(*InitEnvironmentRequest)(nil),   // 6: collector.InitEnvironmentRequest
	(*InitEnvironmentResponse)(nil),  // 7: collector.InitEnvironmentResponse
	(*GetStatesResponse_Metric)(nil), // 8: collector.GetStatesResponse.Metric
	(*ApplyActionsRequest_Knob)(nil), // 9: collector.ApplyActionsRequest.Knob
}
var file_recommendations_api_recommendations_api_proto_depIdxs = []int32{
	8, // 0: collector.GetStatesResponse.Metrics:type_name -> collector.GetStatesResponse.Metric
	9, // 1: collector.ApplyActionsRequest.knobs:type_name -> collector.ApplyActionsRequest.Knob
	0, // 2: collector.RecommendationsAPI.GetStates:input_type -> collector.GetStatesRequest
	2, // 3: collector.RecommendationsAPI.ApplyActions:input_type -> collector.ApplyActionsRequest
	4, // 4: collector.RecommendationsAPI.GetRewardMetrics:input_type -> collector.GetRewardMetricsRequest
	6, // 5: collector.RecommendationsAPI.InitEnvironment:input_type -> collector.InitEnvironmentRequest
	1, // 6: collector.RecommendationsAPI.GetStates:output_type -> collector.GetStatesResponse
	3, // 7: collector.RecommendationsAPI.ApplyActions:output_type -> collector.ApplyActionsResponse
	5, // 8: collector.RecommendationsAPI.GetRewardMetrics:output_type -> collector.GetRewardMetricsResponse
	7, // 9: collector.RecommendationsAPI.InitEnvironment:output_type -> collector.InitEnvironmentResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recommendations_api_recommendations_api_proto_init() }
func file_recommendations_api_recommendations_api_proto_init() {
	if File_recommendations_api_recommendations_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recommendations_api_recommendations_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyActionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyActionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRewardMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRewardMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitEnvironmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitEnvironmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatesResponse_Metric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_api_recommendations_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyActionsRequest_Knob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recommendations_api_recommendations_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendations_api_recommendations_api_proto_goTypes,
		DependencyIndexes: file_recommendations_api_recommendations_api_proto_depIdxs,
		MessageInfos:      file_recommendations_api_recommendations_api_proto_msgTypes,
	}.Build()
	File_recommendations_api_recommendations_api_proto = out.File
	file_recommendations_api_recommendations_api_proto_rawDesc = nil
	file_recommendations_api_recommendations_api_proto_goTypes = nil
	file_recommendations_api_recommendations_api_proto_depIdxs = nil
}
